<a href="https://colab.research.google.com/github/Diego20051219/Actividad_Matrices_537610/blob/main/Te_damos_la_bienvenida_a_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Algoritmo_Valor_Secret

#Start

 # Definir symbols , board , secret_row , secret_col , secret_evalue , guess , size , play_again como Variables
  #Definir Random , Time , Clear_Output como Liberias

  #Def main():
   #  Display ("Bienvenido al juego del valor secreto.") // mensaje de inicio
    # Display ("El juego consiste en memorizar el tablero por unos segundos y luego adivinar el valor oculto.") // mensajes de inicio
    #While true: // ciclo mientras veradero
    #   try:
   #      size = int(input("Ingresa el tamaño del tablero (solo un número):")) // se le agrega valor a size
    #     if play_again <> s: // si no se cumple se acaba el programa
     #        break
    #   except evalueError:
    #     Display "Por favor, ingresa un número válido para el tamaño del tablero." // si ocurre algun error mostrara este mensaje
 # if _name_ = "_main_" :
  # main()

  # Def generate_board(size):
   #   symbols = ['$', '@', '#', 'a', '2', '?', 'g', '+', '5'] // lista de simbolos
   #   board = random.choice([random.randint(1,10)] + symbols)for i in range(size)] for f in range(size)] // donde se genera la board filas y columnas
    #  return board // se retorna

 # Def show_board(board): // imprime las filas de la board
    #  for row in board: // ciclo for
    #   Display (" ".join(str(x) if isinstance(x, int) else x for x in row)) // se ejeuctan la cadenas de enteros y que se impriman bien las filas y el join para separlos

 # Def hide_value(board): // esta funcion escoge un valor en la board y lo oculta para que el usuario la descubra
 #   secret_row = random.randint(0, len(board) - 1) // se escoge un valor de la fila
  #  secret_col = random.randint(0, len(board[0]) - 1) // se escoge un  valor de la columna
  #  secret_value = board[secret_row][secret_col] // y se ajunta en una variable
  #  board[secret_row][secret_col] = '*' // se remplaza por un alterizco
  #  return secret_value, board // y se retorna

# Def play_game(size): // donde se ejucutan todas definiciones
 #   board = generate_board(size)
  #  show_board(board)  // Muestra el tablero completo
  #  Display ("Memoriza el tablero por unos segundos...")
  #  time.sleep(size)  // Se memoriza el tablero para saber cual se oculta el tiempo dependera del valor size
  #  clear_output(wait=True)    // Limpia la salida
 #   secret_value, hidden_board = hide_value(board)
   # show_board(hidden_board)     // Muestra el tablero con el valor oculto
  #  guess = input("Adivina el valor secreto: ")
  #  if str(guess) == str(secret_value):    // se evalua si lo que ingreso el usuario es cierto
  #      Display ("¡Correcto!")    // si es verdadero
  #  else:
  #      Display ("Incorrecto, el valor era:" secret_value) // si es falso

#End

In [ ]:
import random
import time
from IPython.display import clear_output

def generate_board(size):
    symbols = ['$', '@', '#', 'a', '2', '?', 'g', '+', '5']
    board = [[random.choice([random.randint(1, 10)] + symbols) for i in range(size)] for f in range(size)]
    return board

def show_board(board):
    for row in board:
        print(' '.join(str(x) if isinstance(x, int) else x for x in row))

def hide_value(board):
    secret_row = random.randint(0, len(board) - 1)
    secret_col = random.randint(0, len(board[0]) - 1)
    secret_value = board[secret_row][secret_col]
    board[secret_row][secret_col] = '*'
    return secret_value, board

def play_game(size):
    board = generate_board(size)
    show_board(board)  # Muestra el tablero completo
    print("Se ocultara un valor del tablero")
    print("Memoriza el tablero por unos segundos...")
    time.sleep(size)  # Espera size segundos
    clear_output(wait=True)  # Limpia la salida
    secret_value, hidden_board = hide_value(board)
    show_board(hidden_board)  # Muestra el tablero con el valor oculto
    guess = input("Adivina el valor secreto: ")
    if str(guess).lower() == str(secret_value).lower():
        print("¡Correcto!")
    else:
        print("Incorrecto, el valor era:", secret_value)

def main():
    print("Bienvenido al juego del valor secreto.")
    print("El juego consiste en memorizar el tablero por unos segundos y luego adivinar el valor oculto.")
    while True:
        try:
            size = int(input("Ingresa el tamaño del tablero (solo un número): "))
            play_game(size)
            play_again = input("¿Quieres jugar de nuevo? (s/n): ").lower()
            if play_again != 's':
                break
        except ValueError:
            print("Por favor, ingresa un número válido para el tamaño del tablero.")

if __name__ == "__main__":
    main()


In [ ]:

import numpy as np
edades = [18, 17, 23, 43, 54, 12, 23]
edades_array = np.array(edades)
print(edades)
print(edades_array)
print(edades_array.dtype)
print(edades_array.shape)


años_nacimiento = []
for edad in edades:
  años_nacimiento.append(2024 - edad)
print(años_nacimiento)
años_nacimiento_array = 2024 - edades_array
print(años_nacimiento_array)

m = np.array([[1, 2, 3, 0]
              [4, 5, 6, 0]
              [7, 8, 9 ,0]
              [0, 0, 0, 0]])
print(m)
print(m.shape)
print(:, 1)
print(1 , :)


In [ ]:
edades = [18, 17, 23, 43, 54, 12, 23]
edades_array = np.array(edades)
edad_mayor = edades_array <= 18
edades_pares = edades_array[edades_array % 2 == 0 ]
print(edades_pares)
print(edades_array)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
recipes = np.genfromtxt("/content/sample.data/recipes-1.csv", delimiter = "," )
print(recipes)

In [ ]:
a = np.arange(0,10)
b = np.arange(10,20)
c = np.arange(20,30)
matrix_a = np.column_stack([a, b, c])
matrix_b = np.row_stack([a, b, c])
print(matrix_a)
print(matrix_b)
print(f"la suma de la matrix es: {matrix_a.sum()}")


In [ ]:
import numpy as np
a = np.array([1,2])
print(a)




n_10 = np.arange(10)
print(n_10)
n_5_20_3 = np.arange(5,20,3)
print(n_5_20_3)
t = np.linspace(0, 2*np.pi, num=10 )
print(t)


vector_9 =  np.arange(9)
print(vector_9)



n = np.arange(10,20)
print(n)
print(n.sum())

In [40]:
import random
import numpy as np

rng = np.random.default_rng()
rand_1 = rng.integers(-10, 10, size=(3, 3))
rand_2 = rng.standard_normal(size=(3, 3))
print(rand_1)
print(rand_2)

[[ 1  0 -4]
 [ 1  5  8]
 [ 5  6 -1]]
[[ 0.32039697  0.2698451   0.28815332]
 [ 0.42612207 -0.44033936  0.48915172]
 [-1.18128811  1.18407959 -0.75762008]]
